version: '3.8'
services:
  db:
    image: postgres:15
    container_name: fit_manager_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fit_manager
    ports:
      - "5432:5432"
    restart: always