# ---------------------------------------------------------
# CONEXÃO COM O BANCO EM MEMÓRIA (H2)
# ---------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:fit_manager
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ---------------------------------------------------------
# CONFIGURAÇÕES DO HIBERNATE/JPA (Criação de Tabelas)
# ---------------------------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---------------------------------------------------------
# PAINEL DO BANCO NO NAVEGADOR
# ---------------------------------------------------------
# Permite acessar o banco visualmente em: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console